[package]
name = "chan_dupes_rs"
version = "0.1.0"
authors = ["Darryl Imhof <darryl.imhof@gmail.com>"]
edition = "2018"

[dependencies]
regex = "*"
lazy_static = "*"
twox-hash = "*"
clap = "*"
indicatif = "*"


