[package]
name = "chan_dupes_rs"
version = "0.1.0"
authors = ["Darryl Imhof <darryl.imhof@gmail.com>"]

[dependencies]
glob = "*"
walkdir = "*"
regex = "*"
lazy_static = "*"
twox-hash = "*"
pbr = "*"

[dependencies.clap]
version = "*"
default-features = false
