[package]
name = "chan_dupes_rs"
version = "0.1.0"
authors = ["Darryl Imhof <darryl.imhof@gmail.com>"]

[dependencies]
walkdir = "*"
regex = "*"
lazy_static = "*"
twox-hash = "*"
clap = "*"
[dependencies.pbr]
git = "https://github.com/a8m/pb.git"


